{
  # For math-shepherd PRM
  RM: "math-shepherd-mistral-7b-prm",
  cot_task_desc: "",
  cot_examples: "",
  eot_token: null,
  eot_id: null,
  problem_format_str: "{question} {answer}",
  lm_step_tag: null,
  prm_step_tag: "ки\n"
}